### ISSUE TITLE
Feature Request: Sub Tree

### ISSUE THREAD

**Issue by linonetwo** [0xABAD/behavior_tree#10]
How can you concat multiple trees?

So you can keep every tree readable by a human, by keeping it small and abstract.

**Comment by 0xABAD** [comment]
You could have an action of a parent tree represent the evaluation of a sub-tree:

```
?
|    (Foo)
|    [Bar]
```

If `Foo` becomes false then `Bar` is run, which internally runs another tree that it represents.  The result of that sub tree becomes the output of `Bar`.  It's more about the execution mechanism you want to achieve as opposed to syntax.

**Comment by linonetwo** [comment]
Thank you for the explanation, I will try out!
