### ISSUE TITLE
Wrong return value tested for error condition

### ISSUE THREAD

**Issue by jan-dolejsi** [0xABAD/behavior_tree#3]
I started writing tests for corner cases and found this bug:

https://github.com/0xABAD/behavior_tree/blob/47005b56a8796613df3290d11cc260a85aa3ce6d/btree.js#L295

Suggest handling abnormal conditions by exception handling.

**Comment by 0xABAD** [comment]
No, exceptions aren't necessary.  In fact, they are a poor language construct as they introduce an additional exit point of a function that disrupts the control flow.  Just handle the error and if you can't then forward it to the caller.

In this case, the best option is to write a test to assert the correct error condition, which you have already done.  The test brought more value than having to introduce additional (disguised) control flow.

**Comment by 0xABAD** [comment]
Fixed with [commit](https://github.com/0xABAD/behavior_tree/commit/aa1a887005e84ad51fb55a9d4decf6d6f48aaff6).

**Comment by jan-dolejsi** [comment]
Sure, I know the theory, but just saw in practice that while the pattern leads to a more transparent control flow, it makes error handling optional and it is obviously possible to miss an abnormal situation.

**Comment by 0xABAD** [comment]
Exceptions, in general, typically do *become optional*.  Either you have:

* try/catch in parts of the code which you could have done the same with returning errors.
* The global *gotta catch them all* try/catch handler which really can only log the error and then exit the program as you are so far from the error case there is no way of proper recovery.
* Just ignore (or accidentally don't handle) the exceptions all together resulting in a crash.  In some cases a stack trace is printed but has no use to a regular user of the program.  However, in Javascript your page becomes unresponsive (especially with single page apps), and if you're lucky the user will refresh.  If it continues though then they will most likely just leave the page altogether so you were better off not reporting the error in the first place.

Anecdotally speaking, I typically see scenario three.  My biggest gripe about exceptions though is they are not part of an API.  IIRC, Java has checked exceptions but those are pretty nuanced, but every other language that has exceptions does not expose them through any interface.  Instead, you have to rely on the documentation, which isn't compiled or checked by a machine and have to rely on the developers to properly maintain it.  So far the best type of error handling I have seen is in languages like Rust and Haskell where you have a `Result`/`Either` type.  Golang, while more cumbersome, serves as a more happy medium.
