### ISSUE TITLE
Feature suggestion: action activation callbacks

### ISSUE THREAD

**Issue by jan-dolejsi** [0xABAD/behavior_tree#7]
While exploring the programmatic usage of the code, I needed further refinement of the code. Not sure it is still compatible with the philosophy of this repo, so perhaps you want to check it out first by looking at this PR within my fork:
https://github.com/jan-dolejsi/behavior_tree/pull/1

I also added CI that includes validation of all the fenced code samples in the `README.md`.

Let me know if you want to add this stuff.

**Comment by 0xABAD** [comment]
This looks good.  I'd say submit a PR.
